<?php
// Canticle configuration — copy to config.php and fill in your values
// Generated by install.php; you can also edit manually.

return [

    // ── Database ─────────────────────────────────────────────────────────────
    'db_host'     => 'localhost',
    'db_port'     => 3306,
    'db_name'     => 'canticle',
    'db_user'     => 'canticle',
    'db_pass'     => '',
    'db_charset'  => 'utf8mb4',

    // ── Instance ──────────────────────────────────────────────────────────────
    'domain'      => 'social.example.com',          // no https://, no trailing slash
    'site_name'   => 'Canticle',
    'site_desc'   => 'A federated social space.',
    'site_lang'   => 'en',
    'contact_email' => 'admin@example.com',

    // Registrations: 'open' | 'approval' | 'closed'
    'registrations' => 'closed',

    // ── Posting limits ───────────────────────────────────────────────────────
    'max_chars'       => 500,
    'max_poll_options' => 4,
    'max_media'       => 4,         // attachments per post
    'max_media_mb'    => 40,        // upload size in MB

    // ── Security ─────────────────────────────────────────────────────────────
    'app_key'     => '',            // 64-char random hex; generated by install.php
    'app_env'     => 'production',  // 'production' | 'development'

    // ── Storage ──────────────────────────────────────────────────────────────
    'storage_path' => __DIR__ . '/storage',
    'media_url'    => '',           // leave blank to use https://{domain}/media/

    // ── AI Alt Text ──────────────────────────────────────────────────────────
    'alttext_provider' => '',       // 'claude' | 'openai' | 'ollama' | '' (disabled)
    'alttext_api_key'  => '',
    'alttext_model'    => '',       // e.g. claude-haiku-4-5-20251001 / gpt-4o-mini
    'alttext_endpoint' => '',       // only for ollama: http://localhost:11434

    // ── Queue ─────────────────────────────────────────────────────────────────
    // Canticle uses a DB-backed queue. Run worker via: php artisan.php worker
    // Or add a cron: * * * * * php /path/to/canticle/artisan.php worker --once
    'queue_batch_size' => 5,

    // ── Email ─────────────────────────────────────────────────────────────────
    'mail_from'   => 'no-reply@example.com',
    'mail_method' => 'mail',        // 'mail' | 'smtp'
    'smtp_host'   => '',
    'smtp_port'   => 587,
    'smtp_user'   => '',
    'smtp_pass'   => '',
    'smtp_tls'    => true,

    // ── Rate limiting ─────────────────────────────────────────────────────────
    'rate_limit_api'    => 300,     // requests per 5 minutes per token
    'rate_limit_public' => 100,

    // ── Content retention ─────────────────────────────────────────────────────
    // Remote statuses and cached actor profiles older than these limits are
    // automatically deleted by: php artisan.php prune
    // Set to 0 to keep content forever (not recommended on small disks).
    // These are also editable in Admin → Settings → Content Retention.
    'remote_status_max_days' => 90,   // days to keep remote statuses
    'remote_actor_max_days'  => 180,  // days to keep unused remote actor profiles

];
